# Generated by Django 3.0.5 on 2020-04-13 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareas',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='tareas',
            name='titulo',
        ),
    ]
