# Generated by Django 3.0.5 on 2020-04-13 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20200412_2143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tareas',
        ),
    ]
