# Generated by Django 3.0.5 on 2020-04-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_tareas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tareas',
            new_name='Tarea',
        ),
    ]
