# Generated by Django 3.0.5 on 2020-04-25 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_auto_20200414_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='comentarios',
            field=models.TextField(default='Ninguno'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
